/**
 * Supabase integration - write migration files
 */

import path from 'path';
import { writeFile } from '../utils/fileWriter.js';
import { generateTimestamp } from '../utils/timestamp.js';

export function writeSupabaseMigration(sql, message = 'migration', config = {}) {
  const supabaseDir = config.supabaseDir || './supabase/migrations';
  const timestamp = generateTimestamp();
  const filename = `${timestamp}_${sanitizeMessage(message)}.sql`;
  const filePath = path.join(supabaseDir, filename);

  const content = formatMigrationFile(sql);

  return writeFile(filePath, content) ? filePath : null;
}

function sanitizeMessage(message) {
  return message
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function formatMigrationFile(sql) {
  const header = `-- Migration generated by SQLSmith
-- Generated at: ${new Date().toISOString()}

`;

  return header + sql;
}
